name: test_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  progress_bars: ^0.0.3

  # Architecture
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  share: ^2.0.4
  image_picker: ^0.7.0-nullsafety

  touchable: ^1.0.0


  # state management
  provider: ^6.0.0

  visibility_detector: ^0.2.2

  flutter_typeahead: ^3.2.3

  #animations
  animator: 3.1.0

  #crypto and encrypt
  crypto: ^3.0.1
  encrypt: ^5.0.1

  #websocket_page
  stomp_dart_client: ^0.4.3
  web_socket_channel: ^2.1.0

  #platform_widgets
  flutter_platform_widgets: ^1.9.5

  flutter_slidable: ^1.1.0

  #redux
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_thunk: ^0.4.0

  permission_handler: ^8.1.2
  path_provider: ^2.0.5
  flutter_downloader: ^1.7.1
  dio: ^4.0.1

  flowder: ^0.2.0


  flutter_local_notifications: ^9.0.1
  flutter_svg: 0.22.0

  #mockito tests


  # https://gitlab+deploy-token-12:29Fs87Xp17Kxab29h7jU@gitlab.st.by:Tsiuryn_AV/generator_lib.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  test: ^1.9.4


  mockito: ^5.0.17



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/constraint/
    - assets/bird_calc/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
